### ISSUE TITLE
Compile issue?

### ISSUE THREAD

**Issue by ohnx** [IanSeyler/minIP#1]
I seem to have some issues compiling minIP.

In particular, the `struct ifreq` does not seem to be recognized, nor does `IFNAMSIZ` and `IFF_UP`.

Am I missing a header?

**Comment by ohnx** [comment]
Hmm, seems like `net/if.h` isn't working. It might be something with my compiler.

**Comment by IanSeyler** [comment]
Compiles correctly in Ubuntu 15.10. What version of Linux are you using?

**Comment by ohnx** [comment]
The fix seems to be adding `#define __USE_MISC` before including the header.

**Comment by ohnx** [comment]
@IanSeyler I don't actually know, I was using an online compiler. In any case, the fix was whatt I mentioned about.

**Comment by IanSeyler** [comment]
K, closing this!

**Comment by ohnx** [comment]
Would it be possible to add the line mentioned in the actual source?

**Comment by IanSeyler** [comment]
Yep, where did you see that original error come up?

**Comment by ohnx** [comment]
I'll create a pull request.

**Comment by IanSeyler** [comment]
No need! I've already added it on my system with some other changes. Where did you see that error message though?

**Comment by ohnx** [comment]
I used an online C to Assembly (GCC-produced) compiler that can be found [here](https://assembly.ynh.io/).

The exact error given was as follows:

```
Error: Command failed: /tmp/test870050545.c: In function 'net_init':
/tmp/test870050545.c:508:25: error: invalid application of 'sizeof' to incomplete type 'struct ifreq'
  memset(&ifr, 0, sizeof(struct ifreq));
                         ^
/tmp/test870050545.c:509:2: error: invalid use of undefined type 'struct ifreq'
  strncpy(ifr.ifr_name, interface, IFNAMSIZ);
  ^
/tmp/test870050545.c:509:35: error: 'IFNAMSIZ' undeclared (first use in this function)
  strncpy(ifr.ifr_name, interface, IFNAMSIZ);
                                   ^
/tmp/test870050545.c:509:35: note: each undeclared identifier is reported only once for each function it appears in
/tmp/test870050545.c:521:2: error: invalid use of undefined type 'struct ifreq'
  if ((ifr.ifr_flags & IFF_UP) == 0)
  ^
/tmp/test870050545.c:521:23: error: 'IFF_UP' undeclared (first use in this function)
  if ((ifr.ifr_flags & IFF_UP) == 0)
                       ^
/tmp/test870050545.c:540:3: error: invalid use of undefined type 'struct ifreq'
   src_MAC[c] = (unsigned char)ifr.ifr_ifru.ifru_hwaddr.sa_data[c]; // This works... but WTF
   ^
/tmp/test870050545.c:549:2: error: invalid use of undefined type 'struct ifreq'
  sa.sll_ifindex = ifr.ifr_ifindex;
  ^
```
